### ISSUE TITLE
Integrative 

### ISSUE THREAD

**Issue by Panthers12** [Panthers12/DVP1-Notes#1]
Integrative = Notes on Assigned Research.
Credit for 2 hours of integrative / GPS remains in good shape!

**Comment by eMediaLab** [comment]
Research the following:

Classes
Objects
Constructors
Lists

Post a follow-up comment to this issue, with links to the material you looked at.
Also - summarize your thoughts on that material.

**Comment by Panthers12** [comment]
Done!
